# version: "3.9"

volumes:
  prometheus_data: {}

services:
  solar-exporter:
    build: .
    ports:
      - "9560:9560"
    volumes:
      - "./config.yaml:/config.yaml"
      - "/dev:/dev"
    restart: always
    privileged: true
  prometheus:
    image: prom/prometheus:v2.36.2
    volumes:
    - ./example/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    - "prometheus_data:/prometheus"
    command:
    - '--config.file=/etc/prometheus/prometheus.yml'
    - '--storage.tsdb.path=/prometheus'
    ports:
    - "9090:9090"
    environment:
      TZ: "Europe/Moscow"