{
 "title": "SmartWatt ECO",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "serialport",
    "query": {
     "query": "label_values(solar_invertor_batary_voltage,port)"
    }
   },
   {
    "name": "solarpanelchannel",
    "label": "SolarPanelChannel",
    "query": {
     "query": "label_values(solar_invertor_solar_panel_voltage,channel)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Device Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solar_invertor_status{port=\"$serialport\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Invertor temperature",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solar_invertor_temperature{port=\"$serialport\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Input AC Voltage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solar_invertor_input_voltage_ac{port=\"$serialport\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Out AC Voltage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solar_invertor_output_voltage_ac{port=\"$serialport\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Invertor temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "solar_invertor_temperature{port=\"$serialport\"}",
     "legendFormat": "{{port}}"
    }
   ]
  },
  {
   "title": "Active load power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "solar_invertor_output_active_power{port=\"$serialport\"}",
     "legendFormat": "{{port}}"
    }
   ]
  },
  {
   "title": "Reactive load power",
   "type": "timeseries",
   "description": "reactive load",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "voltamp" } },
   "targets": [
    {
     "expr": "solar_invertor_output_apparent_power{port=\"$serialport\"}",
     "legendFormat": "{{port}}"
    }
   ]
  },
  {
   "title": "Solar panel current",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "expr": "solar_invertor_solar_panel_current{port=\"$serialport\"}",
     "legendFormat": "{{port}}"
    }
   ]
  },
  {
   "title": "Input DC info $solarpanelchannel",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "repeat": "solarpanelchannel",
   "collapsed": true,
   "panels": [
    {
     "title": "Volar panel voltage",
     "type": "timeseries",
     "description": "Напряжение канала с солнечными панелями ",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "volt" } },
     "targets": [
      {
       "expr": "solar_invertor_solar_panel_voltage{port=\"$serialport\", channel=\"$solarpanelchannel\"}",
       "legendFormat": "{{port}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Input AC info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Input voltage",
     "type": "timeseries",
     "description": "Incoming voltage from the city network",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "volt" } },
     "targets": [
      {
       "expr": "solar_invertor_input_voltage_ac{port=\"$serialport\"}",
       "legendFormat": "{{port}}"
      }
     ]
    },
    {
     "title": "Voltage frequency",
     "type": "timeseries",
     "description": "Voltage frequency from the city network",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "rothz" } },
     "targets": [
      {
       "expr": "solar_invertor_input_voltage_ac_frequency{port=\"$serialport\"}",
       "legendFormat": "{{port}}"
      }
     ]
    }
   ]
  },
  { "title": "Batary info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Batary voltage",
   "type": "timeseries",
   "description": "battery voltage",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "solar_invertor_batary_voltage{port=\"$serialport\"}",
     "legendFormat": "{{port}}"
    }
   ]
  },
  {
   "title": "Batary charge percent",
   "type": "timeseries",
   "description": "battery percentage",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "solar_invertor_batary_charge_percent{port=\"$serialport\"}",
     "legendFormat": "{{port}}"
    }
   ]
  },
  {
   "title": "Batary charge current",
   "type": "timeseries",
   "description": "battery charging current",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "expr": "solar_invertor_charge_current{port=\"$serialport\"}",
     "legendFormat": "{{port}}"
    }
   ]
  }
 ]
}